[package]
name = "libsystemd-sys"
version = "0.1.0"
authors = ["Richard Markiewicz <rmarkiewicz@devolutions.net>"]
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.17"