[package]
name = "systemd-rs"
version = "0.1.0"
authors = ["Richard Markiewicz <rmarkiewicz@devolutions.net>"]
edition = "2018"

[dependencies]
libsystemd-sys = { path = "libsystemd-sys" }
libc = "0.2"
log = "0.4"
epoll = "4.1.0"